# permissions for end users to view gogoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gogo-viewer-role
rules:
- apiGroups:
  - hello.jonkeam.com
  resources:
  - gogoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello.jonkeam.com
  resources:
  - gogoes/status
  verbs:
  - get
