# permissions for end users to edit gogoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gogo-editor-role
rules:
- apiGroups:
  - hello.jonkeam.com
  resources:
  - gogoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hello.jonkeam.com
  resources:
  - gogoes/status
  verbs:
  - get
